In [1]:
import json

In [2]:
## path to file

json_path =  r'C:\Users\khare\Desktop\LLM_FINAL_PROJ\LLM-Project\Dataset_for_RAG\foodkeeper_USDP.json'
## load the JSON data
with open(json_path, 'r') as f:
    data = json.load(f)

In [3]:
data.keys()

dict_keys(['fileName', 'sheets'])

In [4]:
data['sheets'][1]['data']  ## Contains mapping of food items to their categories [Maps categories to products in sheets[2]['data']]

[[{'ID': 1.0}, {'Category_Name': 'Baby Food'}, {'Subcategory_Name': None}],
 [{'ID': 2.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Bakery'}],
 [{'ID': 3.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Baking and Cooking'}],
 [{'ID': 4.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Refrigerated Dough'}],
 [{'ID': 5.0}, {'Category_Name': 'Beverages'}, {'Subcategory_Name': None}],
 [{'ID': 6.0},
  {'Category_Name': 'Condiments, Sauces & Canned Goods'},
  {'Subcategory_Name': None}],
 [{'ID': 7.0},
  {'Category_Name': 'Dairy Products & Eggs'},
  {'Subcategory_Name': None}],
 [{'ID': 8.0},
  {'Category_Name': 'Food Purchased Frozen'},
  {'Subcategory_Name': None}],
 [{'ID': 9.0},
  {'Category_Name': 'Grains, Beans & Pasta'},
  {'Subcategory_Name': None}],
 [{'ID': 10.0}, {'Category_Name': 'Meat'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 11.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Shelf Stable Foods'}],
 [{'ID': 12.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Smoked or Processed'}],
 [{'ID': 13.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Stuffed or Assembled'}],
 [{'ID': 14.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Cooked or Processed'}],
 [{'ID': 15.0}, {'Category_Name': 'Poultry'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 16.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Shelf Stable Foods'}],
 [{'ID': 17.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Stuffed or Assembled'}],
 [{'ID': 18.0},
  {'Category_Name': 'Produce'},
  {'Subcategory_Name': 'Fresh Fruits'}],
 [{'ID': 19.0},
  {'Category_Name': 'Produce'},
  {'Subcategory_Name': 'Fresh Vegetables'}],
 [{'ID': 20.0}, {'Category_Name': 'Seafood'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 21.0},
  {'Category_Name': 'Seafood'},
  {'Subcategory_Name': 'Shellfish'}],
 [{'ID': 22.0}, {'Category_Name': 'Seafood'}, {'Subcategory_Name': 'Smoked'}],
 [{'ID': 23.0},
  {'Category_Name': 'Shelf Stable Foods'},
  {'Subcategory_Name': None}],
 [{'ID': 24.0},
  {'Category_Name': 'Vegetarian Proteins'},
  {'Subcategory_Name': None}],
 [{'ID': 25.0},
  {'Category_Name': 'Deli & Prepared Foods'},
  {'Subcategory_Name': None}]]

In [5]:
data['sheets'][2]['data']   # Different products and their details (expiry time, storage conditions, etc.)  -> 661 products

[[{'ID': 1.0},
  {'Category_ID': 7.0},
  {'Name': 'Butter'},
  {'Name_subtitle': None},
  {'Keywords': 'Butter'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': 'May be left at room temperature for 1 - 2 days.'},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Months'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 6.0},
  {'DOP_Freeze_Max': 9.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 2.0},
  {'Category_ID': 7.0},
  {'Name': 'Buttermilk'},
  {'Name_subtitle': None},
  {'Keywords': 'Buttermilk'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 3.0},
  {'DOP_Freeze_Max': 3.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 3.0},
  {'Category_ID': 7.0},
  {'Name': 'Cheese'},
  {'Name_subtitle': 'hard such as cheddar, swiss, block parmesan'},
  {'Keywords': 'Cheese,cheddar, swiss,parmesan'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 6.0},
  {'DOP_Refrigerate_Max': 6.0},
  {'DOP_Refrigerate_Metric': 'Months'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': 3.0},
  {'Refrigerate_After_Opening_Max': 4.0},
  {'Refrigerate_After_Opening_Metric': 'Weeks'},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 6.0},
  {'DOP_Freeze_Max': 6.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 4.0},
  {'Category_ID': 7.0},
  {'Name': 'Cheese'},
  {'Name_subtitle': 'parmesan; shredded or grated'},
  {'Keywords': 'Cheese,parmesan,shredded,grated'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 12.0},
  {'DOP_Refrigerate_Max': 12.0},
  {'DOP_Refrigerate_Metric': 'Months'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 5.0},
  {'Category_ID': 7.0},
  {'Name': 'Cheese'},
  {'Name_subtitle': 'shredded; cheddar, mozzarella, etc.'},
  {'Keywords': 'Cheese,shredded,cheddar,mozzarella'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 1.0},
  {'DOP_Refrigerate_Metric': 'Months'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 3.0},
  {'DOP_Freeze_Max': 4.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 6.0},
  {'Category_ID': 7.0},
  {'Name': 'Cheese'},
  {'Name_subtitle': 'processed slices'},
  {'Keywords': 'Cheese,processed slices,slices,slice'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 3.0},
  {'DOP_Refrigerate_Max': 4.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 7.0},
  {'Category_ID': 7.0},
  {'Name': 'Cheese'},
  {'Name_subtitle': 'soft such as brie, bel paese, goat'},
  {'Keywords': 'Cheese,brie, bel paese, goat'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 6.0},
  {'DOP_Freeze_Max': 6.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 8.0},
  {'Category_ID': 7.0},
  {'Name': 'Coffee creamer'},
  {'Name_subtitle': 'liquid refrigerated'},
  {'Keywords': 'Coffee creamer,Coffee, creamer,liquid refrigerated'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 3.0},
  {'DOP_Refrigerate_Max': 3.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None}],
 [{'ID': 9.0},
  {'Category_ID': 7.0},
  {'Name': 'Cottage cheese'},
  {'Name_subtitle': None},
  {'Keywords': 'Cottage cheese,cheese'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 2.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': 1.0},
  {'Refrigerate_After_Opening_Max': 1.0},
  {'Refrigerate_After_Opening_Metric': 'Weeks'},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 10.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream cheese'},
  {'Name_subtitle': None},
  {'Keywords': None},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 2.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 11.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream'},
  {'Name_subtitle': 'whipping, ultrapasteurized'},
  {'Keywords': 'Cream,whipping,ultrapasteurized'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 1.0},
  {'DOP_Refrigerate_Metric': 'Months'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': 1.0},
  {'Refrigerate_After_Opening_Max': 1.0},
  {'Refrigerate_After_Opening_Metric': 'Weeks'},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 12.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream'},
  {'Name_subtitle': 'whipped, sweetened'},
  {'Keywords': 'Cream,whipped, sweetened'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': 1.0},
  {'Refrigerate_Max': 1.0},
  {'Refrigerate_Metric': 'Days'},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': None},
  {'DOP_Refrigerate_Max': None},
  {'DOP_Refrigerate_Metric': None},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': 1.0},
  {'Freeze_Max': 2.0},
  {'Freeze_Metric': 'Months'},
  {'Freeze_Tips': None}],
 [{'ID': 13.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream'},
  {'Name_subtitle': 'half and half'},
  {'Keywords': 'Cream,half'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 3.0},
  {'DOP_Refrigerate_Max': 4.0},
  {'DOP_Refrigerate_Metric': 'Days'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 4.0},
  {'DOP_Freeze_Max': 4.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 14.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream'},
  {'Name_subtitle': 'heavy'},
  {'Keywords': 'Cream,heavy'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 10.0},
  {'DOP_Refrigerate_Max': 10.0},
  {'DOP_Refrigerate_Metric': 'Days'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': None},
  {'DOP_Freeze_Min': 3.0},
  {'DOP_Freeze_Max': 4.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 15.0},
  {'Category_ID': 7.0},
  {'Name': 'Cream'},
  {'Name_subtitle': 'light'},
  {'Keywords': 'Cream,light'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 1.0},
  {'DOP_Refrigerate_Max': 1.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': None},
  {'Freeze_Tips': 'Use for cooking.'},
  {'DOP_Freeze_Min': 3.0},
  {'DOP_Freeze_Max': 4.0},
  {'DOP_Freeze_Metric': 'Months'},
  {'DOP_Freeze_Tips': None}],
 [{'ID': 16.0},
  {'Category_ID': 7.0},
  {'Name': 'Dips'},
  {'Name_subtitle': 'sour cream based'},
  {'Keywords': 'Dips,sour cream based,sour,cream based,cream,dip'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 2.0},
  {'DOP_Refrigerate_Max': 2.0},
  {'DOP_Refrigerate_Metric': 'Weeks'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': None},
  {'Refrigerate_After_Opening_Max': None},
  {'Refrigerate_After_Opening_Metric': None},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 17.0},
  {'Category_ID': 7.0},
  {'Name': 'Egg substitutes'},
  {'Name_subtitle': 'liquid'},
  {'Keywords': 'Egg substitutes,liquid,egg,substitutes,substitute'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},
  {'Refrigerate_Min': None},
  {'Refrigerate_Max': None},
  {'Refrigerate_Metric': None},
  {'Refrigerate_tips': None},
  {'DOP_Refrigerate_Min': 7.0},
  {'DOP_Refrigerate_Max': 7.0},
  {'DOP_Refrigerate_Metric': 'Days'},
  {'DOP_Refrigerate_tips': None},
  {'Refrigerate_After_Opening_Min': 3.0},
  {'Refrigerate_After_Opening_Max': 3.0},
  {'Refrigerate_After_Opening_Metric': 'Days'},
  {'Refrigerate_After_Thawing_Min': None},
  {'Refrigerate_After_Thawing_Max': None},
  {'Refrigerate_After_Thawing_Metric': None},
  {'Freeze_Min': None},
  {'Freeze_Max': None},
  {'Freeze_Metric': 'Not Recommended'},
  {'Freeze_Tips': None}],
 [{'ID': 20.0},
  {'Category_ID': 7.0},
  {'Name': 'Eggnog'},
  {'Name_subtitle': 'commercial'},
  {'Keywords': 'Eggnog,commercial,egg,nog'},
  {'Pantry_Min': None},
  {'Pantry_Max': None},
  {'Pantry_Metric': None},
  {'Pantry_tips': None},
  {'DOP_Pantry_Min': None},
  {'DOP_Pantry_Max': None},
  {'DOP_Pantry_Metric': None},
  {'DOP_Pantry_tips': None},
  {'Pantry_After_Opening_Min': None},
  {'Pantry_After_Opening_Max': None},
  {'Pantry_After_Opening_Metric': None},

In [6]:
data['sheets'][3]['data'] ## Maps products to theur tempreature, also contains some tips --> 93 only
## Only some products have this information

[[{'ID': 1.0},
  {'Product_ID': 21.0},
  {'Tips': 'Cook until yolk and white are firm.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 2.0},
  {'Product_ID': 24.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 3.0},
  {'Product_ID': 34.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 4.0},
  {'Product_ID': 35.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 5.0},
  {'Product_ID': 36.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 6.0},
  {'Product_ID': 37.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 7.0},
  {'Product_ID': 38.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 8.0},
  {'Product_ID': 39.0},
  {'Tips': 'Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 9.0},
  {'Product_ID': 40.0},
  {'Tips': 'Cooking times are per side. Use a food thermometer to check internal temperature, and cook longer if below safe temperature.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 10.0},
  {'Product_ID': 41.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 11.0},
  {'Product_ID': 42.0},
  {'Tips': 'Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 12.0},
  {'Product_ID': 43.0},
  {'Tips': 'Cooking suggestions are for burgers. Cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 13.0},
  {'Product_ID': 44.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 14.0},
  {'Product_ID': 45.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 15.0},
  {'Product_ID': 46.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 16.0},
  {'Product_ID': 47.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 17.0},
  {'Product_ID': 48.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 18.0},
  {'Product_ID': 49.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 19.0},
  {'Product_ID': 50.0},
  {'Tips': 'Cooking suggestions are for burgers. Cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None}],
 [{'ID': 20.0},
  {'Product_ID': 51.0},
  {'Tips': 'Cooking times are per side.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 21.0},
  {'Product_ID': 52.0},
  {'Tips': 'Cook 4 inches from heat.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 22.0},
  {'Product_ID': 53.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 23.0},
  {'Product_ID': 54.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 24.0},
  {'Product_ID': 55.0},
  {'Tips': 'Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 25.0},
  {'Product_ID': 56.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 26.0},
  {'Product_ID': 57.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 27.0},
  {'Product_ID': 58.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 28.0},
  {'Product_ID': 59.0},
  {'Tips': 'Cooking suggestions are for burgers. Cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None}],
 [{'ID': 29.0},
  {'Product_ID': 60.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 30.0},
  {'Product_ID': 61.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 34.0},
  {'Product_ID': 63.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 37.0},
  {'Product_ID': 64.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 38.0},
  {'Product_ID': 65.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 39.0},
  {'Product_ID': 66.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 40.0},
  {'Product_ID': 67.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 41.0},
  {'Product_ID': 67.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 43.0},
  {'Product_ID': 69.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 46.0},
  {'Product_ID': 72.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 48.0},
  {'Product_ID': 73.0},
  {'Tips': 'cooking suggestions are for burgers. cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 49.0},
  {'Product_ID': 74.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 50.0},
  {'Product_ID': 75.0},
  {'Tips': 'When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 51.0},
  {'Product_ID': 76.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None}],
 [{'ID': 53.0},
  {'Product_ID': 83.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 54.0},
  {'Product_ID': 84.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 55.0},
  {'Product_ID': 85.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 56.0},
  {'Product_ID': 86.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 57.0},
  {'Product_ID': 87.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None}],
 [{'ID': 58.0},
  {'Product_ID': 88.0},
  {'Tips': 'Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F.'},
  {'Safe_Minimum_Temperature': 140.0},
  {'Rest_Time': None}],
 [{'ID': 59.0},
  {'Product_ID': 89.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 60.0},
  {'Product_ID': 90.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 61.0},
  {'Product_ID': 91.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 62.0},
  {'Product_ID': 92.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 63.0},
  {'Product_ID': 93.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 64.0},
  {'Product_ID': 94.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 65.0},
  {'Product_ID': 95.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 66.0},
  {'Product_ID': 96.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 67.0},
  {'Product_ID': 97.0},
  {'Tips': 'Before cooking, soak 4 to 12 hours with water in the refrigerator. After boiling, drain, glaze, and brown at 400°F for 15 minutes.'},
  {'Safe_Minimum_Temperature': None}],
 [{'ID': 68.0},
  {'Product_ID': 113.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 69.0},
  {'Product_ID': 114.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 70.0},
  {'Product_ID': 115.0},
  {'Tips': 'Cooking suggestions are for burgers. Cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 71.0},
  {'Product_ID': 116.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 72.0},
  {'Product_ID': 117.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 73.0},
  {'Product_ID': 118.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 74.0},
  {'Product_ID': 119.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 75.0},
  {'Product_ID': 120.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 76.0},
  {'Product_ID': 121.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 77.0},
  {'Product_ID': 122.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Add 15 to 30 minutes for stuffed birds. The internal temperature should reach 165°F in the center of the stuffing.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 78.0},
  {'Product_ID': 123.0},
  {'Tips': 'Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 79.0},
  {'Product_ID': 124.0},
  {'Tips': 'Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 80.0},
  {'Product_ID': 125.0},
  {'Tips': 'Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 81.0},
  {'Product_ID': 126.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 82.0},
  {'Product_ID': 127.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 83.0},
  {'Product_ID': 128.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 84.0},
  {'Product_ID': 129.0},
  {'Tips': 'Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 85.0},
  {'Product_ID': 144.0},
  {'Tips': 'Cook until flesh is opaque and separates easily with a fork.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 86.0},
  {'Product_ID': 145.0},
  {'Tips': 'Cook until flesh is opaque and separates easily with a fork.'},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 87.0},
  {'Product_ID': 146.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': None}],
 [{'ID': 88.0},
  {'Product_ID': 150.0},
  {'Tips': 'Cook until flesh is milky white or opaque and firm.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 89.0},
  {'Product_ID': 151.0},
  {'Tips': 'Cook until flesh is pearly and opaque.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 90.0},
  {'Product_ID': 154.0},
  {'Tips': 'Cook until flesh is pearly and opaque.'},
  {'Safe_Minimum_Temperature': None}],
 [{'ID': 91.0},
  {'Product_ID': 157.0},
  {'Tips': 'Cook until shells open during cooking.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 92.0},
  {'Product_ID': 158.0},
  {'Tips': 'Cook until flesh is pearly and opaque.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 93.0},
  {'Product_ID': 159.0},
  {'Tips': 'Cook until flesh is pearly and opaque.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 94.0},
  {'Product_ID': 160.0},
  {'Tips': 'Cook until shells open during cooking.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 95.0},
  {'Product_ID': 161.0},
  {'Tips': 'Cook until flesh is pearly and opaque.'},
  {'Safe_Minimum_Temperature': None},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 96.0},
  {'Product_ID': 194.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None},
  {'Rest_Time_metric': None}],
 [{'ID': 97.0},
  {'Product_ID': 81.0},
  {'Tips': 'Cooking methods apply covered in water.'},
  {'Safe_Minimum_Temperature': None}],
 [{'ID': 98.0},
  {'Product_ID': 106.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 145.0},
  {'Rest_Time': 3.0},
  {'Rest_Time_metric': 'minutes'}],
 [{'ID': 99.0},
  {'Product_ID': 132.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 100.0},
  {'Product_ID': 134.0},
  {'Tips': 'Follow packaging directions.'},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 101.0},
  {'Product_ID': 135.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 102.0},
  {'Product_ID': 141.0},
  {'Tips': None},
  {'Safe_Minimum_Temperature': 165.0},
  {'Rest_Time': None}],
 [{'ID': 105.0},
  {'Product_ID': 78.0},
  {'Tips': 'Cooking suggestions are for burgers. Cooking times are per side if grilling.'},
  {'Safe_Minimum_Temperature': 160.0},
  {'Rest_Time': None}]]

Based on this, this is how the current structure is 


Sheet 1: Categories (ID → Category_Name, Subcategory_Name)


Sheet 2: Products (ID, Category_ID → links to Sheet 1, plus storage data)


Sheet 3: Safety Tips (ID, Product_ID → links to Sheet 2)

In [7]:
import json
import pandas as pd

with open(r'C:\Users\khare\Desktop\LLM_FINAL_PROJ\LLM-Project\Dataset_for_RAG\foodkeeper_USDP.json', 'r') as f:
    data = json.load(f)

# Extract sheets
categories_data = data['sheets'][1]['data']  # Sheet 1
products_data = data['sheets'][2]['data']    # Sheet 2  
safety_data = data['sheets'][3]['data']      # Sheet 3
cooking_data = data['sheets'][4]['data']     # Sheet 4

In [8]:
len(categories_data), len(products_data), len(safety_data), len(cooking_data)

(25, 661, 93, 89)

In [9]:
categories_data

[[{'ID': 1.0}, {'Category_Name': 'Baby Food'}, {'Subcategory_Name': None}],
 [{'ID': 2.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Bakery'}],
 [{'ID': 3.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Baking and Cooking'}],
 [{'ID': 4.0},
  {'Category_Name': 'Baked Goods'},
  {'Subcategory_Name': 'Refrigerated Dough'}],
 [{'ID': 5.0}, {'Category_Name': 'Beverages'}, {'Subcategory_Name': None}],
 [{'ID': 6.0},
  {'Category_Name': 'Condiments, Sauces & Canned Goods'},
  {'Subcategory_Name': None}],
 [{'ID': 7.0},
  {'Category_Name': 'Dairy Products & Eggs'},
  {'Subcategory_Name': None}],
 [{'ID': 8.0},
  {'Category_Name': 'Food Purchased Frozen'},
  {'Subcategory_Name': None}],
 [{'ID': 9.0},
  {'Category_Name': 'Grains, Beans & Pasta'},
  {'Subcategory_Name': None}],
 [{'ID': 10.0}, {'Category_Name': 'Meat'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 11.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Shelf Stable Foods'}],
 [{'ID': 12.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Smoked or Processed'}],
 [{'ID': 13.0},
  {'Category_Name': 'Meat'},
  {'Subcategory_Name': 'Stuffed or Assembled'}],
 [{'ID': 14.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Cooked or Processed'}],
 [{'ID': 15.0}, {'Category_Name': 'Poultry'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 16.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Shelf Stable Foods'}],
 [{'ID': 17.0},
  {'Category_Name': 'Poultry'},
  {'Subcategory_Name': 'Stuffed or Assembled'}],
 [{'ID': 18.0},
  {'Category_Name': 'Produce'},
  {'Subcategory_Name': 'Fresh Fruits'}],
 [{'ID': 19.0},
  {'Category_Name': 'Produce'},
  {'Subcategory_Name': 'Fresh Vegetables'}],
 [{'ID': 20.0}, {'Category_Name': 'Seafood'}, {'Subcategory_Name': 'Fresh'}],
 [{'ID': 21.0},
  {'Category_Name': 'Seafood'},
  {'Subcategory_Name': 'Shellfish'}],
 [{'ID': 22.0}, {'Category_Name': 'Seafood'}, {'Subcategory_Name': 'Smoked'}],
 [{'ID': 23.0},
  {'Category_Name': 'Shelf Stable Foods'},
  {'Subcategory_Name': None}],
 [{'ID': 24.0},
  {'Category_Name': 'Vegetarian Proteins'},
  {'Subcategory_Name': None}],
 [{'ID': 25.0},
  {'Category_Name': 'Deli & Prepared Foods'},
  {'Subcategory_Name': None}]]

In [10]:
cooking_data

[[{'ID': 1.0},
  {'Product_ID': 34.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 2.0},
  {'Product_ID': 35.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 28.0},
  {'Timing_to': 38.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 3.0},
  {'Product_ID': 36.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.5},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 4.0},
  {'Product_ID': 37.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 5.0},
  {'Product_ID': 38.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 3.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 35.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 6.0},
  {'Product_ID': 39.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 7.0},
  {'Product_ID': 40.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': None},
  {'Measure_to': None},
  {'Size_metric': None},
  {'Cooking_Temperature': None},
  {'Timing_from': 4.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 8.0},
  {'Product_ID': 41.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 2.0},
  {'Timing_to': 3.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 9.0},
  {'Product_ID': 42.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 10.0},
  {'Product_ID': 43.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 11.0},
  {'Product_ID': 44.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 12.0},
  {'Product_ID': 45.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 13.0},
  {'Product_ID': 46.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 14.0},
  {'Product_ID': 47.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 375.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 15.0},
  {'Product_ID': 48.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 16.0},
  {'Product_ID': 49.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 12.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 17.0},
  {'Product_ID': 50.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 18.0},
  {'Product_ID': 51.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 11.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 19.0},
  {'Product_ID': 52.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 14.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 20.0},
  {'Product_ID': 53.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 21.0},
  {'Product_ID': 54.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 22.0},
  {'Product_ID': 55.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 1.5},
  {'Measure_to': 2.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 23.0},
  {'Product_ID': 56.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 24.0},
  {'Product_ID': 57.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 25.0},
  {'Product_ID': 58.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 34.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 26.0},
  {'Product_ID': 59.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 27.0},
  {'Product_ID': 60.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 28.0},
  {'Product_ID': 61.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 33.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 29.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 9.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 30.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 4.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 31.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 32.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 12.0},
  {'Timing_to': 16.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 33.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 34.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 35.0},
  {'Product_ID': 65.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 36.0},
  {'Product_ID': 66.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 37.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': '425-450'},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 38.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 39.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 40.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 41.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 42.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 43.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 44.0},
  {'Product_ID': 73.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 45.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 45.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 46.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 2.0},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 47.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 48.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 49.0},
  {'Product_ID': 76.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 50.0},
  {'Product_ID': 83.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 51.0},
  {'Product_ID': 84.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 24.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 52.0},
  {'Product_ID': 85.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 53.0},
  {'Product_ID': 86.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 54.0},
  {'Product_ID': 87.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 55.0},
  {'Product_ID': 88.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 12.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 56.0},
  {'Product_ID': 89.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 57.0},
  {'Product_ID': 90.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 58.0},
  {'Product_ID': 91.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 59.0},
  {'Product_ID': 92.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 60.0},
  {'Product_ID': 93.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 61.0},
  {'Product_ID': 94.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 8.0},
  {'Measure_to': 20.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 26.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 62.0},
  {'Product_ID': 95.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 24.0},
  {'Timing_to': 28.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 63.0},
  {'Product_ID': 96.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 64.0},
  {'Product_ID': 97.0},
  {'Cooking_Method': 'Boil'},
  {'Measure_from': 6.0},
  {'Measure_to': 16.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 65.0},
  {'Product_ID': 113.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 66.0},
  {'Product_ID': 114.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 24.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 67.0},
  {'Product_ID': 115.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 68.0},
  {'Product_ID': 116.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 30.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 69.0},
  {'Product_ID': 117.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],

In [11]:
cooking_data

[[{'ID': 1.0},
  {'Product_ID': 34.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 2.0},
  {'Product_ID': 35.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 28.0},
  {'Timing_to': 38.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 3.0},
  {'Product_ID': 36.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.5},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 4.0},
  {'Product_ID': 37.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 5.0},
  {'Product_ID': 38.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 3.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 35.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 6.0},
  {'Product_ID': 39.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 7.0},
  {'Product_ID': 40.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': None},
  {'Measure_to': None},
  {'Size_metric': None},
  {'Cooking_Temperature': None},
  {'Timing_from': 4.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 8.0},
  {'Product_ID': 41.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 2.0},
  {'Timing_to': 3.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 9.0},
  {'Product_ID': 42.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 10.0},
  {'Product_ID': 43.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 11.0},
  {'Product_ID': 44.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 12.0},
  {'Product_ID': 45.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 13.0},
  {'Product_ID': 46.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 14.0},
  {'Product_ID': 47.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 375.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 15.0},
  {'Product_ID': 48.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 16.0},
  {'Product_ID': 49.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 12.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 17.0},
  {'Product_ID': 50.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 18.0},
  {'Product_ID': 51.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 11.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 19.0},
  {'Product_ID': 52.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 14.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 20.0},
  {'Product_ID': 53.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 21.0},
  {'Product_ID': 54.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 22.0},
  {'Product_ID': 55.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 1.5},
  {'Measure_to': 2.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 23.0},
  {'Product_ID': 56.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 24.0},
  {'Product_ID': 57.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 25.0},
  {'Product_ID': 58.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 34.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 26.0},
  {'Product_ID': 59.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 27.0},
  {'Product_ID': 60.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 28.0},
  {'Product_ID': 61.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 33.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 29.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 9.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 30.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 4.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 31.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 32.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 12.0},
  {'Timing_to': 16.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 33.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 34.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 35.0},
  {'Product_ID': 65.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 36.0},
  {'Product_ID': 66.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 37.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': '425-450'},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 38.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 39.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 40.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 41.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 42.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 43.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 44.0},
  {'Product_ID': 73.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 45.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 45.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 46.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 2.0},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 47.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 48.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 49.0},
  {'Product_ID': 76.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 50.0},
  {'Product_ID': 83.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 51.0},
  {'Product_ID': 84.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 24.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 52.0},
  {'Product_ID': 85.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 53.0},
  {'Product_ID': 86.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 54.0},
  {'Product_ID': 87.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 55.0},
  {'Product_ID': 88.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 12.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 56.0},
  {'Product_ID': 89.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 57.0},
  {'Product_ID': 90.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 58.0},
  {'Product_ID': 91.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 59.0},
  {'Product_ID': 92.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 60.0},
  {'Product_ID': 93.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 61.0},
  {'Product_ID': 94.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 8.0},
  {'Measure_to': 20.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 26.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 62.0},
  {'Product_ID': 95.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 24.0},
  {'Timing_to': 28.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 63.0},
  {'Product_ID': 96.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 64.0},
  {'Product_ID': 97.0},
  {'Cooking_Method': 'Boil'},
  {'Measure_from': 6.0},
  {'Measure_to': 16.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 65.0},
  {'Product_ID': 113.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 66.0},
  {'Product_ID': 114.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 24.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 67.0},
  {'Product_ID': 115.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 68.0},
  {'Product_ID': 116.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 30.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 69.0},
  {'Product_ID': 117.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],

In [12]:
import json
import re
import pandas as pd

def flatten_sheet(sheet_data):
    """Convert nested list-of-dicts to flat dict and return as DataFrame."""
    flattened = []
    for record in sheet_data:
        flat = {}
        for field_dict in record:
            for key, value in field_dict.items():
                flat[key] = value
        flattened.append(flat)
    return pd.DataFrame(flattened)

# Load and flatten all sheets
## Changing the structure from [[{'ID': 1}, {'Name': 'Butter'}, {'Keywords': 'Butter'}], ...] --> [{'ID': 1, 'Name': 'Butter', 'Keywords': 'Butter'}, ...] --> DataFrame
categories_df = flatten_sheet(data['sheets'][1]['data'])
products_df = flatten_sheet(data['sheets'][2]['data'])
safety_df = flatten_sheet(data['sheets'][3]['data'])
cooking_df = flatten_sheet(data['sheets'][4]['data'])

In [13]:
## This format is converted to a dataframe format
cooking_data

[[{'ID': 1.0},
  {'Product_ID': 34.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 2.0},
  {'Product_ID': 35.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 28.0},
  {'Timing_to': 38.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 3.0},
  {'Product_ID': 36.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.5},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 4.0},
  {'Product_ID': 37.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 5.0},
  {'Product_ID': 38.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 3.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 425.0},
  {'Timing_from': 35.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 6.0},
  {'Product_ID': 39.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 7.0},
  {'Product_ID': 40.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': None},
  {'Measure_to': None},
  {'Size_metric': None},
  {'Cooking_Temperature': None},
  {'Timing_from': 4.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 8.0},
  {'Product_ID': 41.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 2.0},
  {'Timing_to': 3.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 9.0},
  {'Product_ID': 42.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 10.0},
  {'Product_ID': 43.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 5.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 11.0},
  {'Product_ID': 44.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 12.0},
  {'Product_ID': 45.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 13.0},
  {'Product_ID': 46.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 14.0},
  {'Product_ID': 47.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 375.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 15.0},
  {'Product_ID': 48.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 16.0},
  {'Product_ID': 49.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 12.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 17.0},
  {'Product_ID': 50.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 18.0},
  {'Product_ID': 51.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 11.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 19.0},
  {'Product_ID': 52.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 14.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 20.0},
  {'Product_ID': 53.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 21.0},
  {'Product_ID': 54.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 22.0},
  {'Product_ID': 55.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 1.5},
  {'Measure_to': 2.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.0},
  {'Timing_to': 1.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 23.0},
  {'Product_ID': 56.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 24.0},
  {'Product_ID': 57.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 25.0},
  {'Product_ID': 58.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 34.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 26.0},
  {'Product_ID': 59.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 27.0},
  {'Product_ID': 60.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 5.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 28.0},
  {'Product_ID': 61.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 23.0},
  {'Timing_to': 33.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 29.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 9.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 30.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 3.0},
  {'Timing_to': 4.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 31.0},
  {'Product_ID': 63.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 32.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.75},
  {'Measure_to': 1.5},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 12.0},
  {'Timing_to': 16.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 33.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 7.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 34.0},
  {'Product_ID': 64.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.25},
  {'Measure_to': 0.75},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 6.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 35.0},
  {'Product_ID': 65.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 36.0},
  {'Product_ID': 66.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 37.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': '425-450'},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 38.0},
  {'Product_ID': 67.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.5},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 39.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 40.0},
  {'Product_ID': 69.0},
  {'Cooking_Method': 'Skillet'},
  {'Measure_from': 0.5},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 8.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 41.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 42.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 43.0},
  {'Product_ID': 72.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 1.5},
  {'Timing_to': 2.0},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 44.0},
  {'Product_ID': 73.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 10.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 45.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 45.0},
  {'Timing_to': 45.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 46.0},
  {'Product_ID': 74.0},
  {'Cooking_Method': 'Braise'},
  {'Measure_from': 3.0},
  {'Measure_to': 6.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 2.0},
  {'Timing_to': 2.5},
  {'Timing_metric': 'hours'},
  {'Timing_per': None}],
 [{'ID': 47.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Broil/Grill'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 48.0},
  {'Product_ID': 75.0},
  {'Cooking_Method': 'Cover with liquid; simmer'},
  {'Measure_from': 1.0},
  {'Measure_to': 1.0},
  {'Size_metric': 'inches'},
  {'Cooking_Temperature': None},
  {'Timing_from': 45.0},
  {'Timing_to': 60.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 49.0},
  {'Product_ID': 76.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 50.0},
  {'Product_ID': 83.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 51.0},
  {'Product_ID': 84.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 24.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 52.0},
  {'Product_ID': 85.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 7.0},
  {'Measure_to': 9.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 18.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 53.0},
  {'Product_ID': 86.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 25.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 54.0},
  {'Product_ID': 87.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 10.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 15.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 55.0},
  {'Product_ID': 88.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 12.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 10.0},
  {'Timing_to': 15.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 56.0},
  {'Product_ID': 89.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 10.0},
  {'Measure_to': 14.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 18.0},
  {'Timing_to': 20.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 57.0},
  {'Product_ID': 90.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 58.0},
  {'Product_ID': 91.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 3.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 59.0},
  {'Product_ID': 92.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 35.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 60.0},
  {'Product_ID': 93.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 2.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 61.0},
  {'Product_ID': 94.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 8.0},
  {'Measure_to': 20.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 22.0},
  {'Timing_to': 26.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 62.0},
  {'Product_ID': 95.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 24.0},
  {'Timing_to': 28.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 63.0},
  {'Product_ID': 96.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 35.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 64.0},
  {'Product_ID': 97.0},
  {'Cooking_Method': 'Boil'},
  {'Measure_from': 6.0},
  {'Measure_to': 16.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': None},
  {'Timing_from': 20.0},
  {'Timing_to': 25.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 65.0},
  {'Product_ID': 113.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 5.0},
  {'Measure_to': 7.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 66.0},
  {'Product_ID': 114.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 24.0},
  {'Size_metric': 'pounds'},
  {'Cooking_Temperature': 325.0},
  {'Timing_from': 30.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': 'pound'}],
 [{'ID': 67.0},
  {'Product_ID': 115.0},
  {'Cooking_Method': 'Broil/Grill/Fry'},
  {'Measure_from': 4.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': None},
  {'Timing_from': 5.0},
  {'Timing_to': 8.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 68.0},
  {'Product_ID': 116.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 6.0},
  {'Measure_to': 8.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 30.0},
  {'Timing_to': 40.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],
 [{'ID': 69.0},
  {'Product_ID': 117.0},
  {'Cooking_Method': 'Oven'},
  {'Measure_from': 4.0},
  {'Measure_to': 4.0},
  {'Size_metric': 'ounces'},
  {'Cooking_Temperature': 350.0},
  {'Timing_from': 20.0},
  {'Timing_to': 30.0},
  {'Timing_metric': 'minutes'},
  {'Timing_per': None}],

In [14]:
cooking_df

,ID,Product_ID,Cooking_Method,Measure_from,Measure_to,Size_metric,Cooking_Temperature,Timing_from,Timing_to,Timing_metric,Timing_per
0,1.0,34.0,Oven,4.0,8.0,pounds,325.0,23.0,30.0,minutes,pound
1,2.0,35.0,Oven,4.0,6.0,pounds,325.0,28.0,38.0,minutes,pound
2,3.0,36.0,Oven,2.5,4.0,pounds,325.0,30.0,35.0,minutes,pound
3,4.0,37.0,Oven,4.0,6.0,pounds,425.0,45.0,60.0,minutes,None
4,5.0,38.0,Oven,2.0,3.0,pounds,425.0,35.0,45.0,minutes,None
...,...,...,...,...,...,...,...,...,...,...,...
84,85.0,106.0,Broil/Grill,1.0,1.5,inches,None,20.0,35.0,minutes,None
85,86.0,132.0,Broil/Grill,1.0,1.5,inches,None,20.0,35.0,minutes,None
86,87.0,135.0,Oven,NaN,NaN,None,325.0,NaN,NaN,NaN,NaN
87,88.0,141.0,Oven,NaN,NaN,None,325.0,30.0,30.0,minutes,None
88,92.0,78.0,Broil/Grill/Fry,4.0,8.0,ounces,None,5.0,8.0,minutes,None

In [15]:
# Rename columns for clarity
## Because there are multiple ID's in each sheets
## Renaming them to be more specific for merging later

products_df = products_df.rename(columns={'ID': 'Product_ID'})
safety_df = safety_df.rename(columns={'ID': 'Safety_ID', 'Product_ID': 'Product_ID'})
cooking_df = cooking_df.rename(columns={'ID': 'Cooking_ID', 'Product_ID': 'Product_ID'})

In [16]:
# Add category names to products
## Categories has ID and Name, Products has Product Id and category ID, merging them to get category name in products dataframe
products_with_cat = products_df.merge(
    categories_df, 
    left_on='Category_ID', 
    right_on='ID', 
    how='left'
)

products_with_cat.iloc[15:45]

,Product_ID,Category_ID,Name,Name_subtitle,Keywords,Pantry_Min,Pantry_Max,Pantry_Metric,Pantry_tips,DOP_Pantry_Min,...,Freeze_Max,Freeze_Metric,Freeze_Tips,DOP_Freeze_Min,DOP_Freeze_Max,DOP_Freeze_Metric,DOP_Freeze_Tips,ID,Category_Name,Subcategory_Name
15,16.0,7.0,Dips,sour cream based,"Dips,sour cream based,sour,cream based,cream,dip",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
16,17.0,7.0,Egg substitutes,liquid,"Egg substitutes,liquid,egg,substitutes,substitute",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
17,20.0,7.0,Eggnog,commercial,"Eggnog,commercial,egg,nog",NaN,NaN,None,None,NaN,...,NaN,None,None,6.0,6.0,Months,None,7.0,Dairy Products & Eggs,None
18,21.0,7.0,Eggs,in shell,"Eggs,in shell,egg,shell",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
19,22.0,7.0,Eggs,"raw whites, yolks","Eggs,raw whites, yolks,egg,whites",NaN,NaN,None,None,NaN,...,12.0,Months,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
20,23.0,7.0,Eggs,hard boiled cooked,"Eggs,egg,hard boiled cooked,boiled,hard boiled",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
21,24.0,7.0,Egg dishes,None,"Egg dishes,egg,dishes",NaN,NaN,None,None,NaN,...,3.0,Months,Freezing guidance applies to egg dishes after ...,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
22,25.0,7.0,Kefir,fermented milk,"Kefir,fermented milk,milk,fermented",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
23,26.0,7.0,Margarine,None,Margarine,NaN,NaN,None,None,NaN,...,NaN,None,None,12.0,12.0,Months,None,7.0,Dairy Products & Eggs,None
24,27.0,7.0,Milk,plain or flavored,"Milk,plain,flavored,flavor",NaN,NaN,None,None,NaN,...,NaN,None,None,3.0,3.0,Months,None,7.0,Dairy Products & Eggs,None
25,28.0,7.0,Pudding,None,Pudding,NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
26,29.0,7.0,Sour cream,None,"Sour cream,cream,sour",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
27,30.0,7.0,Whipped cream,aerosol can,"Whipped cream,cream,aerosol can,can",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
28,31.0,7.0,Whipped topping,aerosol can,"Whipped topping,topping,aerosol can,can,whipped",NaN,NaN,None,None,NaN,...,NaN,Not Recommended,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
29,32.0,7.0,Whipped topping,tub,"Whipped topping,topping,tub,whipped",NaN,NaN,None,None,NaN,...,14.0,Months,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
30,33.0,7.0,Yogurt,None,Yogurt,NaN,NaN,None,None,NaN,...,2.0,Months,None,NaN,NaN,NaN,NaN,7.0,Dairy Products & Eggs,None
31,34.0,10.0,Beef,"rib roast, bone-in","Beef,rib roast,bone-in,roast,bone,rib",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
32,35.0,10.0,Beef,"rib roast; boneless, rolled","Beef,rib roast,boneless,rolled,roast,rib",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
33,36.0,10.0,Beef,round or rump roast,"Beef,round,rump roast,roast",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
34,37.0,10.0,Beef,"tenderloin, whole","Beef,tenderloin,whole",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
35,38.0,10.0,Beef,"tenderloin, half","Beef,tenderloin,half",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
36,39.0,10.0,Beef,"chuck roast, brisket","Beef,chuck roast,roast,brisket",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
37,40.0,10.0,Beef,steaks,"Beef,steaks,steak",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
38,41.0,10.0,Beef,"stew, cubes","Beef,stew, cubes,cube",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
39,42.0,10.0,Beef,short ribs,"Beef,short ribs,ribs,rib",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
40,43.0,10.0,Beef,ground,"Beef,ground",NaN,NaN,None,None,NaN,...,NaN,None,None,3.0,4.0,Months,None,10.0,Meat,Fresh
41,44.0,10.0,Lamb,"leg, bone-in - small","Lamb,leg,bone-in - small,bone-in,bone",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
42,45.0,10.0,Lamb,"leg, bone-in - large","Lamb,leg,bone-in - large,bone-in,bone",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
43,46.0,10.0,Lamb,"leg; boneless, rolled","Lamb,leg,boneless,rolled,bone",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh
44,47.0,10.0,Lamb,crown roast,"Lamb,crown roast,roast",NaN,NaN,None,None,NaN,...,NaN,None,None,4.0,12.0,Months,None,10.0,Meat,Fresh

In [17]:
def get_specific_name(food_name, keywords):
    """Extract specific variety from keywords
       Essential for varieties of meats cuts, to prevent duplication and for more clarity in the documents. For example, if the food item is 'Beef' and the keywords contain 'rib roast',
     we can name the document 'Beef (Rib Roast)' instead of just 'Beef', which gives more specific information about the product.
    """
    if pd.isna(keywords) or keywords == food_name:
        return food_name
    keywords_lower = str(keywords).lower()
    
    # take first unique keyword
    kw_list = [k.strip() for k in keywords_lower.split(',')]
    for kw in kw_list:
        if kw != food_name.lower() and len(kw) > 2:
            return f"{food_name} ({kw.title()})"
    
    return food_name

In [18]:
# === STORAGE DOCUMENTS (661 records) ===
storage_docs = []

for _, row in products_with_cat.iterrows():
    food_name = row.get('Name', 'Unknown') ## Getting the name of the food item, if not present, default to 'Unknown'
    if pd.isna(food_name):
        continue

    keywords = row.get('Keywords', '')
    specific_name = get_specific_name(food_name, keywords)  ## Getting the specific name of the food item based on its keywords, for more clarity in the documents. For example, if the food item is 'Beef' and the keywords contain 'rib roast', we can name the document 'Beef (Rib Roast)' instead of just 'Beef', which gives more specific information about the product.
    
    # Build rich storage text
    ## Idea is to get Pantry info, Refrigerator info (from purchase and after opening) and combine them into a single text field for each product

    storage_parts = []
    
    # Pantry info  ## Some products have pantry tips, if present, we add it to the storage info.
    if pd.notna(row.get('Pantry_tips')):
        storage_parts.append(f"Pantry: {row['Pantry_tips']}")
    
    # Date of Purchase - Refrigerator 
    ## DOP refrigerate min and max gives the range of days for which the product can be stored in the refrigerator from the date of purchase, if both values are present, we add it to the storage info.
    if pd.notna(row.get('DOP_Refrigerate_Min')) and pd.notna(row.get('DOP_Refrigerate_Max')):
        min_val = int(row['DOP_Refrigerate_Min']) if row['DOP_Refrigerate_Min'] % 1 == 0 else row['DOP_Refrigerate_Min']  ## %1 ==0 is just to check if the value is a whole number, if yes, we convert it to int to remove the decimal point, otherwise we keep it as is (could be a fraction or a decimal)
        max_val = int(row['DOP_Refrigerate_Max']) if row['DOP_Refrigerate_Max'] % 1 == 0 else row['DOP_Refrigerate_Max']
        metric = row.get('DOP_Refrigerate_Metric', 'days')
        storage_parts.append(f"Refrigerator (from purchase): {min_val}-{max_val} {metric}")
    
    # After opening
    if pd.notna(row.get('Refrigerate_After_Opening_Min')) and pd.notna(row.get('Refrigerate_After_Opening_Max')):
        min_val = int(row['Refrigerate_After_Opening_Min']) if row['Refrigerate_After_Opening_Min'] % 1 == 0 else row['Refrigerate_After_Opening_Min']
        max_val = int(row['Refrigerate_After_Opening_Max']) if row['Refrigerate_After_Opening_Max'] % 1 == 0 else row['Refrigerate_After_Opening_Max']
        metric = row.get('Refrigerate_After_Opening_Metric', 'days')  ## Getting the metric for after opening, if not present, default to 'days'
        storage_parts.append(f"Refrigerator (after opening): {min_val}-{max_val} {metric}")
    
    if storage_parts:
        search_text = f"{food_name} {row.get('Keywords', '')} {row.get('Category_Name', '')}"  ## Makes it easier to search for the product based on its name, keywords and category. Essentially added for RAG retrieval purposes, so that the relevant document can be retrieved based on the query.
        
        storage_docs.append({
            'id': f"storage_{row['Product_ID']}",
            'food_name': specific_name,
            'category': row.get('Category_Name'),
            'subcategory': row.get('Subcategory_Name'),
            'content': f"{keywords}. " + " | ".join(storage_parts),  ## Joining the different storage parts with a seperator. Include important contents in one line
            'search_text': search_text.lower(),
            'type': 'storage'
        })

In [19]:
storage_docs

[{'id': 'storage_1.0',
  'food_name': 'Butter',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Butter. Pantry: May be left at room temperature for 1 - 2 days. | Refrigerator (from purchase): 1-2 Months',
  'search_text': 'butter butter dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_2.0',
  'food_name': 'Buttermilk',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Buttermilk. Refrigerator (from purchase): 1-2 Weeks',
  'search_text': 'buttermilk buttermilk dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_3.0',
  'food_name': 'Cheese (Cheddar)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cheese,cheddar, swiss,parmesan. Refrigerator (from purchase): 6-6 Months | Refrigerator (after opening): 3-4 Weeks',
  'search_text': 'cheese cheese,cheddar, swiss,parmesan dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_4.0',
  'food_name': 'Cheese (Parmesan)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cheese,parmesan,shredded,grated. Refrigerator (from purchase): 12-12 Months',
  'search_text': 'cheese cheese,parmesan,shredded,grated dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_5.0',
  'food_name': 'Cheese (Shredded)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cheese,shredded,cheddar,mozzarella. Refrigerator (from purchase): 1-1 Months',
  'search_text': 'cheese cheese,shredded,cheddar,mozzarella dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_6.0',
  'food_name': 'Cheese (Processed Slices)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cheese,processed slices,slices,slice. Refrigerator (from purchase): 3-4 Weeks',
  'search_text': 'cheese cheese,processed slices,slices,slice dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_7.0',
  'food_name': 'Cheese (Brie)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cheese,brie, bel paese, goat. Refrigerator (from purchase): 1-2 Weeks',
  'search_text': 'cheese cheese,brie, bel paese, goat dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_8.0',
  'food_name': 'Coffee creamer (Coffee)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Coffee creamer,Coffee, creamer,liquid refrigerated. Refrigerator (from purchase): 3-3 Weeks',
  'search_text': 'coffee creamer coffee creamer,coffee, creamer,liquid refrigerated dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_9.0',
  'food_name': 'Cottage cheese (Cheese)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cottage cheese,cheese. Refrigerator (from purchase): 2-2 Weeks | Refrigerator (after opening): 1-1 Weeks',
  'search_text': 'cottage cheese cottage cheese,cheese dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_10.0',
  'food_name': 'Cream cheese',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'None. Refrigerator (from purchase): 2-2 Weeks',
  'search_text': 'cream cheese none dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_11.0',
  'food_name': 'Cream (Whipping)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cream,whipping,ultrapasteurized. Refrigerator (from purchase): 1-1 Months | Refrigerator (after opening): 1-1 Weeks',
  'search_text': 'cream cream,whipping,ultrapasteurized dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_13.0',
  'food_name': 'Cream (Half)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cream,half. Refrigerator (from purchase): 3-4 Days',
  'search_text': 'cream cream,half dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_14.0',
  'food_name': 'Cream (Heavy)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cream,heavy. Refrigerator (from purchase): 10-10 Days',
  'search_text': 'cream cream,heavy dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_15.0',
  'food_name': 'Cream (Light)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Cream,light. Refrigerator (from purchase): 1-1 Weeks',
  'search_text': 'cream cream,light dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_16.0',
  'food_name': 'Dips (Sour Cream Based)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Dips,sour cream based,sour,cream based,cream,dip. Refrigerator (from purchase): 2-2 Weeks',
  'search_text': 'dips dips,sour cream based,sour,cream based,cream,dip dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_17.0',
  'food_name': 'Egg substitutes (Liquid)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Egg substitutes,liquid,egg,substitutes,substitute. Refrigerator (from purchase): 7-7 Days | Refrigerator (after opening): 3-3 Days',
  'search_text': 'egg substitutes egg substitutes,liquid,egg,substitutes,substitute dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_20.0',
  'food_name': 'Eggnog (Commercial)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Eggnog,commercial,egg,nog. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'eggnog eggnog,commercial,egg,nog dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_21.0',
  'food_name': 'Eggs (In Shell)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Eggs,in shell,egg,shell. Refrigerator (from purchase): 3-5 Weeks',
  'search_text': 'eggs eggs,in shell,egg,shell dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_25.0',
  'food_name': 'Kefir (Fermented Milk)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Kefir,fermented milk,milk,fermented. Refrigerator (from purchase): 1-1 Weeks | Refrigerator (after opening): 1-2 Days',
  'search_text': 'kefir kefir,fermented milk,milk,fermented dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_26.0',
  'food_name': 'Margarine',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Margarine. Refrigerator (from purchase): 6-6 Months',
  'search_text': 'margarine margarine dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_28.0',
  'food_name': 'Pudding',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Pudding. Refrigerator (after opening): 2-2 Days',
  'search_text': 'pudding pudding dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_30.0',
  'food_name': 'Whipped cream (Cream)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Whipped cream,cream,aerosol can,can. Refrigerator (from purchase): 3-4 Weeks',
  'search_text': 'whipped cream whipped cream,cream,aerosol can,can dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_31.0',
  'food_name': 'Whipped topping (Topping)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Whipped topping,topping,aerosol can,can,whipped. Refrigerator (from purchase): 3-3 Months',
  'search_text': 'whipped topping whipped topping,topping,aerosol can,can,whipped dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_32.0',
  'food_name': 'Whipped topping (Topping)',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Whipped topping,topping,tub,whipped. Refrigerator (from purchase): 2-2 Weeks',
  'search_text': 'whipped topping whipped topping,topping,tub,whipped dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_33.0',
  'food_name': 'Yogurt',
  'category': 'Dairy Products & Eggs',
  'subcategory': None,
  'content': 'Yogurt. Refrigerator (from purchase): 1-2 Weeks',
  'search_text': 'yogurt yogurt dairy products & eggs',
  'type': 'storage'},
 {'id': 'storage_34.0',
  'food_name': 'Beef (Rib Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,rib roast,bone-in,roast,bone,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,rib roast,bone-in,roast,bone,rib meat',
  'type': 'storage'},
 {'id': 'storage_35.0',
  'food_name': 'Beef (Rib Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,rib roast,boneless,rolled,roast,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,rib roast,boneless,rolled,roast,rib meat',
  'type': 'storage'},
 {'id': 'storage_36.0',
  'food_name': 'Beef (Round)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,round,rump roast,roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,round,rump roast,roast meat',
  'type': 'storage'},
 {'id': 'storage_37.0',
  'food_name': 'Beef (Tenderloin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,tenderloin,whole. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,tenderloin,whole meat',
  'type': 'storage'},
 {'id': 'storage_38.0',
  'food_name': 'Beef (Tenderloin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,tenderloin,half. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,tenderloin,half meat',
  'type': 'storage'},
 {'id': 'storage_39.0',
  'food_name': 'Beef (Chuck Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,chuck roast,roast,brisket. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,chuck roast,roast,brisket meat',
  'type': 'storage'},
 {'id': 'storage_40.0',
  'food_name': 'Beef (Steaks)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,steaks,steak. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,steaks,steak meat',
  'type': 'storage'},
 {'id': 'storage_41.0',
  'food_name': 'Beef (Stew)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,stew, cubes,cube. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,stew, cubes,cube meat',
  'type': 'storage'},
 {'id': 'storage_42.0',
  'food_name': 'Beef (Short Ribs)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,short ribs,ribs,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'beef beef,short ribs,ribs,rib meat',
  'type': 'storage'},
 {'id': 'storage_43.0',
  'food_name': 'Beef (Ground)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Beef,ground. Refrigerator (from purchase): 1-2 Days',
  'search_text': 'beef beef,ground meat',
  'type': 'storage'},
 {'id': 'storage_44.0',
  'food_name': 'Lamb (Leg)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,leg,bone-in - small,bone-in,bone. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,leg,bone-in - small,bone-in,bone meat',
  'type': 'storage'},
 {'id': 'storage_45.0',
  'food_name': 'Lamb (Leg)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,leg,bone-in - large,bone-in,bone. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,leg,bone-in - large,bone-in,bone meat',
  'type': 'storage'},
 {'id': 'storage_46.0',
  'food_name': 'Lamb (Leg)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,leg,boneless,rolled,bone. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,leg,boneless,rolled,bone meat',
  'type': 'storage'},
 {'id': 'storage_47.0',
  'food_name': 'Lamb (Crown Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,crown roast,roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,crown roast,roast meat',
  'type': 'storage'},
 {'id': 'storage_48.0',
  'food_name': 'Lamb (Shoulder Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,shoulder roast,roast,shoulder,shank leg half,half,shank,shank leg,leg. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,shoulder roast,roast,shoulder,shank leg half,half,shank,shank leg,leg meat',
  'type': 'storage'},
 {'id': 'storage_49.0',
  'food_name': 'Lamb (Cubes)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,cubes,kabobs,cube,kabob. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,cubes,kabobs,cube,kabob meat',
  'type': 'storage'},
 {'id': 'storage_50.0',
  'food_name': 'Lamb (Ground)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,ground. Refrigerator (from purchase): 1-2 Days',
  'search_text': 'lamb lamb,ground meat',
  'type': 'storage'},
 {'id': 'storage_51.0',
  'food_name': 'Lamb (Chops)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,chops,ribs,loin,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,chops,ribs,loin,rib meat',
  'type': 'storage'},
 {'id': 'storage_52.0',
  'food_name': 'Lamb (Leg Steaks)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,leg steaks,steaks,steak,leg. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,leg steaks,steaks,steak,leg meat',
  'type': 'storage'},
 {'id': 'storage_53.0',
  'food_name': 'Lamb (Stew)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,stew,pieces,stew meat,meat,piece. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,stew,pieces,stew meat,meat,piece meat',
  'type': 'storage'},
 {'id': 'storage_54.0',
  'food_name': 'Lamb (Shanks)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,shanks,shank. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,shanks,shank meat',
  'type': 'storage'},
 {'id': 'storage_55.0',
  'food_name': 'Lamb (Breast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Lamb,breast,rolled. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'lamb lamb,breast,rolled meat',
  'type': 'storage'},
 {'id': 'storage_56.0',
  'food_name': 'Veal (Shoulder)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Veal,shoulder,boneless,shoulder roast,roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'veal veal,shoulder,boneless,shoulder roast,roast meat',
  'type': 'storage'},
 {'id': 'storage_57.0',
  'food_name': 'Veal (Leg Rump)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Veal,leg rump,rump,leg,round,round roast,roast,boneless. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'veal veal,leg rump,rump,leg,round,round roast,roast,boneless meat',
  'type': 'storage'},
 {'id': 'storage_58.0',
  'food_name': 'Veal (Loin Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Veal,loin roast,bone-in,roast,bone,loin. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'veal veal,loin roast,bone-in,roast,bone,loin meat',
  'type': 'storage'},
 {'id': 'storage_59.0',
  'food_name': 'Veal (Ground)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Veal,ground. Refrigerator (from purchase): 1-2 Days',
  'search_text': 'veal veal,ground meat',
  'type': 'storage'},
 {'id': 'storage_60.0',
  'food_name': 'Pork (Loin Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,loin roast,bone-in,roast,bone,loin. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,loin roast,bone-in,roast,bone,loin meat',
  'type': 'storage'},
 {'id': 'storage_61.0',
  'food_name': 'Pork (Loin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,loin,boneless,loin roast,roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,loin,boneless,loin roast,roast meat',
  'type': 'storage'},
 {'id': 'storage_63.0',
  'food_name': 'Pork (Loin Chops)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,loin chops,bone-in,chops,bone,loin. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,loin chops,bone-in,chops,bone,loin meat',
  'type': 'storage'},
 {'id': 'storage_64.0',
  'food_name': 'Pork (Loin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,loin,boneless,loin chops,chops. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,loin,boneless,loin chops,chops meat',
  'type': 'storage'},
 {'id': 'storage_65.0',
  'food_name': 'Pork (Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,roast,crown,crown roast - small,small,crown roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,roast,crown,crown roast - small,small,crown roast meat',
  'type': 'storage'},
 {'id': 'storage_66.0',
  'food_name': 'Pork (Roast)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,roast,crown,crown roast - large,large,crown roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,roast,crown,crown roast - large,large,crown roast meat',
  'type': 'storage'},
 {'id': 'storage_67.0',
  'food_name': 'Pork (Tenderloin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,tenderloin. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,tenderloin meat',
  'type': 'storage'},
 {'id': 'storage_69.0',
  'food_name': 'Pork (Tenderloin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,tenderloin,tenderloin medallions,loin cubes,medallion,loin cube,loin,medallions,cube,cubes. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,tenderloin,tenderloin medallions,loin cubes,medallion,loin cube,loin,medallions,cube,cubes meat',
  'type': 'storage'},
 {'id': 'storage_70.0',
  'food_name': 'Goat (Tender Whole Cuts)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Goat,tender whole cuts,legs,ribs,shoulder,loin,tender,whole cuts,leg,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'goat goat,tender whole cuts,legs,ribs,shoulder,loin,tender,whole cuts,leg,rib meat',
  'type': 'storage'},
 {'id': 'storage_71.0',
  'food_name': 'Goat (Less Tender Whole Cuts)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Goat,less tender whole cuts,stew meat,stew,meat,riblets,shanks,whole cuts,tender,less tender. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'goat goat,less tender whole cuts,stew meat,stew,meat,riblets,shanks,whole cuts,tender,less tender meat',
  'type': 'storage'},
 {'id': 'storage_72.0',
  'food_name': 'Pork (Ribs)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,ribs,rib. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,ribs,rib meat',
  'type': 'storage'},
 {'id': 'storage_73.0',
  'food_name': 'Pork (Ground)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,ground. Refrigerator (from purchase): 1-2 Days',
  'search_text': 'pork pork,ground meat',
  'type': 'storage'},
 {'id': 'storage_74.0',
  'food_name': 'Pork (Shoulder)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,shoulder. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,shoulder meat',
  'type': 'storage'},
 {'id': 'storage_75.0',
  'food_name': 'Pork (Loin)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Pork,loin,cubes,cube. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'pork pork,loin,cubes,cube meat',
  'type': 'storage'},
 {'id': 'storage_76.0',
  'food_name': 'Venison (Rump)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Venison,rump,round,loin,rib,rib roast,roast. Refrigerator (from purchase): 3-5 Days',
  'search_text': 'venison venison,rump,round,loin,rib,rib roast,roast meat',
  'type': 'storage'},
 {'id': 'storage_77.0',
  'food_name': 'Variety meats (Liver)',
  'category': 'Meat',
  'subcategory': 'Fresh',
  'content': 'Variety meats,liver,tongue,chitterlings,meats,meat,chitterling. Refrigerator (from purchase): 1-2 Days',
  'search_text': 'variety meats variety meats,liver,tongue,chitterlings,meats,meat,chitterling meat',
  'type': 'storage'},
 {'id': 'storage_78.0',
  'food_name': 'Goat (Ground)',
  'category': 'Meat',
  'subcategory': 'Fresh',

In [20]:
# === SAFETY DOCUMENTS ===
safety_docs = []

# Merge safety with products to get food names
safety_with_names = safety_df.merge(
    products_df[['Product_ID', 'Name','Keywords' ,'Category_ID']], 
    on='Product_ID', 
    how='left'
)

for _, row in safety_with_names.iterrows():
    food_name = row.get('Name', 'Unknown')
    if pd.isna(food_name):
        continue
    
    keywords = row.get('Keywords', '')
    specific_name = get_specific_name(food_name, keywords)  ## Getting the specific name of
    safety_parts = []
    
    if pd.notna(row.get('Tips')):
        safety_parts.append(f"Tip: {row['Tips']}")
    
    if pd.notna(row.get('Safe_Minimum_Temperature')):
        temp = int(row['Safe_Minimum_Temperature']) if row['Safe_Minimum_Temperature'] % 1 == 0 else row['Safe_Minimum_Temperature']
        safety_parts.append(f"Cook to {temp}°F")
        
        if pd.notna(row.get('Rest_Time')):
            rest = int(row['Rest_Time']) if row['Rest_Time'] % 1 == 0 else row['Rest_Time']
            metric = row.get('Rest_Time_metric', 'minutes')  ## Getting the metric for rest time, if not present, default to 'minutes'
            safety_parts.append(f"Rest for {rest} {metric}")
    
    if safety_parts:
        safety_docs.append({
            'id': f"safety_{row['Product_ID']}",
            'food_name': specific_name,
            'content': f"{specific_name}. " + " | ".join(safety_parts),
            'search_text': f"{specific_name} temperature cook safe".lower(),
            'type': 'safety'
        })

In [21]:
safety_docs

[{'id': 'safety_21.0',
  'food_name': 'Eggs (In Shell)',
  'content': 'Eggs (In Shell). Tip: Cook until yolk and white are firm.',
  'search_text': 'eggs (in shell) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_24.0',
  'food_name': 'Egg dishes (Egg)',
  'content': 'Egg dishes (Egg). Cook to 160°F',
  'search_text': 'egg dishes (egg) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_34.0',
  'food_name': 'Beef (Rib Roast)',
  'content': 'Beef (Rib Roast). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (rib roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_35.0',
  'food_name': 'Beef (Rib Roast)',
  'content': 'Beef (Rib Roast). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (rib roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_36.0',
  'food_name': 'Beef (Round)',
  'content': 'Beef (Round). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (round) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_37.0',
  'food_name': 'Beef (Tenderloin)',
  'content': 'Beef (Tenderloin). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (tenderloin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_38.0',
  'food_name': 'Beef (Tenderloin)',
  'content': 'Beef (Tenderloin). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (tenderloin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_39.0',
  'food_name': 'Beef (Chuck Roast)',
  'content': 'Beef (Chuck Roast). Tip: Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (chuck roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_40.0',
  'food_name': 'Beef (Steaks)',
  'content': 'Beef (Steaks). Tip: Cooking times are per side. Use a food thermometer to check internal temperature, and cook longer if below safe temperature. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (steaks) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_41.0',
  'food_name': 'Beef (Stew)',
  'content': 'Beef (Stew). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'beef (stew) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_42.0',
  'food_name': 'Beef (Short Ribs)',
  'content': 'Beef (Short Ribs). Tip: Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F',
  'search_text': 'beef (short ribs) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_43.0',
  'food_name': 'Beef (Ground)',
  'content': 'Beef (Ground). Tip: Cooking suggestions are for burgers. Cooking times are per side if grilling. | Cook to 160°F',
  'search_text': 'beef (ground) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_44.0',
  'food_name': 'Lamb (Leg)',
  'content': 'Lamb (Leg). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (leg) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_45.0',
  'food_name': 'Lamb (Leg)',
  'content': 'Lamb (Leg). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (leg) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_46.0',
  'food_name': 'Lamb (Leg)',
  'content': 'Lamb (Leg). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (leg) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_47.0',
  'food_name': 'Lamb (Crown Roast)',
  'content': 'Lamb (Crown Roast). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (crown roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_48.0',
  'food_name': 'Lamb (Shoulder Roast)',
  'content': 'Lamb (Shoulder Roast). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (shoulder roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_49.0',
  'food_name': 'Lamb (Cubes)',
  'content': 'Lamb (Cubes). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (cubes) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_50.0',
  'food_name': 'Lamb (Ground)',
  'content': 'Lamb (Ground). Tip: Cooking suggestions are for burgers. Cooking times are per side if grilling. | Cook to 160°F',
  'search_text': 'lamb (ground) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_51.0',
  'food_name': 'Lamb (Chops)',
  'content': 'Lamb (Chops). Tip: Cooking times are per side. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (chops) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_52.0',
  'food_name': 'Lamb (Leg Steaks)',
  'content': 'Lamb (Leg Steaks). Tip: Cook 4 inches from heat. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (leg steaks) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_53.0',
  'food_name': 'Lamb (Stew)',
  'content': 'Lamb (Stew). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (stew) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_54.0',
  'food_name': 'Lamb (Shanks)',
  'content': 'Lamb (Shanks). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (shanks) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_55.0',
  'food_name': 'Lamb (Breast)',
  'content': 'Lamb (Breast). Tip: Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'lamb (breast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_56.0',
  'food_name': 'Veal (Shoulder)',
  'content': 'Veal (Shoulder). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'veal (shoulder) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_57.0',
  'food_name': 'Veal (Leg Rump)',
  'content': 'Veal (Leg Rump). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'veal (leg rump) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_58.0',
  'food_name': 'Veal (Loin Roast)',
  'content': 'Veal (Loin Roast). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'veal (loin roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_59.0',
  'food_name': 'Veal (Ground)',
  'content': 'Veal (Ground). Tip: Cooking suggestions are for burgers. Cooking times are per side if grilling. | Cook to 160°F',
  'search_text': 'veal (ground) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_60.0',
  'food_name': 'Pork (Loin Roast)',
  'content': 'Pork (Loin Roast). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (loin roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_61.0',
  'food_name': 'Pork (Loin)',
  'content': 'Pork (Loin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (loin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_63.0',
  'food_name': 'Pork (Loin Chops)',
  'content': 'Pork (Loin Chops). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (loin chops) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_64.0',
  'food_name': 'Pork (Loin)',
  'content': 'Pork (Loin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (loin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_65.0',
  'food_name': 'Pork (Roast)',
  'content': 'Pork (Roast). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_66.0',
  'food_name': 'Pork (Roast)',
  'content': 'Pork (Roast). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (roast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_67.0',
  'food_name': 'Pork (Tenderloin)',
  'content': 'Pork (Tenderloin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (tenderloin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_67.0',
  'food_name': 'Pork (Tenderloin)',
  'content': 'Pork (Tenderloin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (tenderloin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_69.0',
  'food_name': 'Pork (Tenderloin)',
  'content': 'Pork (Tenderloin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (tenderloin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_72.0',
  'food_name': 'Pork (Ribs)',
  'content': 'Pork (Ribs). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (ribs) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_73.0',
  'food_name': 'Pork (Ground)',
  'content': 'Pork (Ground). Tip: cooking suggestions are for burgers. cooking times are per side if grilling. | Cook to 160°F',
  'search_text': 'pork (ground) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_74.0',
  'food_name': 'Pork (Shoulder)',
  'content': 'Pork (Shoulder). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. Braising is roasting or simmering less-tender meats with a small amount of liquid in a tightly covered pan. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (shoulder) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_75.0',
  'food_name': 'Pork (Loin)',
  'content': 'Pork (Loin). Tip: When cooked to safe temperatures, fresh pork may still be pink inside - but it will be safe. | Cook to 145°F | Rest for 3 minutes',
  'search_text': 'pork (loin) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_76.0',
  'food_name': 'Venison (Rump)',
  'content': 'Venison (Rump). Cook to 160°F',
  'search_text': 'venison (rump) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_83.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_84.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_85.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_86.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_87.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_88.0',
  'food_name': 'Ham (Fully Cooked)',
  'content': 'Ham (Fully Cooked). Tip: Reheat cooked hams packaged in USDA-inspected plants to 140°F and all others to 165°F. | Cook to 140°F',
  'search_text': 'ham (fully cooked) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_89.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_90.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_91.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_92.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_93.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_94.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_95.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_96.0',
  'food_name': 'Ham (Fresh)',
  'content': 'Ham (Fresh). Cook to 145°F | Rest for 3 minutes',
  'search_text': 'ham (fresh) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_97.0',
  'food_name': 'Ham (Country Ham)',
  'content': 'Ham (Country Ham). Tip: Before cooking, soak 4 to 12 hours with water in the refrigerator. After boiling, drain, glaze, and brown at 400°F for 15 minutes.',
  'search_text': 'ham (country ham) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_113.0',
  'food_name': 'Chicken (Whole)',
  'content': 'Chicken (Whole). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'chicken (whole) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_114.0',
  'food_name': 'Turkey (Whole)',
  'content': 'Turkey (Whole). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'turkey (whole) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_115.0',
  'food_name': 'Ground turkey or chicken (Ground Turkey)',
  'content': 'Ground turkey or chicken (Ground Turkey). Tip: Cooking suggestions are for burgers. Cooking times are per side if grilling. | Cook to 165°F',
  'search_text': 'ground turkey or chicken (ground turkey) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_116.0',
  'food_name': 'Chicken parts (Breast Halves)',
  'content': 'Chicken parts (Breast Halves). Cook to 165°F',
  'search_text': 'chicken parts (breast halves) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_117.0',
  'food_name': 'Chicken parts (Breast Halves)',
  'content': 'Chicken parts (Breast Halves). Cook to 165°F',
  'search_text': 'chicken parts (breast halves) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_118.0',
  'food_name': 'Chicken parts (Legs)',
  'content': 'Chicken parts (Legs). Cook to 165°F',
  'search_text': 'chicken parts (legs) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_119.0',
  'food_name': 'Turkey parts (Breast Halves)',
  'content': 'Turkey parts (Breast Halves). Cook to 165°F',
  'search_text': 'turkey parts (breast halves) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_120.0',
  'food_name': 'Turkey parts (Breast)',
  'content': 'Turkey parts (Breast). Cook to 165°F',
  'search_text': 'turkey parts (breast) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_121.0',
  'food_name': 'Turkey parts (Legs)',
  'content': 'Turkey parts (Legs). Cook to 165°F',
  'search_text': 'turkey parts (legs) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_123.0',
  'food_name': 'Duckling (Domestic)',
  'content': 'Duckling (Domestic). Tip: Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. | Cook to 165°F',
  'search_text': 'duckling (domestic) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_125.0',
  'food_name': 'Goose (Domestic)',
  'content': 'Goose (Domestic). Tip: Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. | Cook to 165°F',
  'search_text': 'goose (domestic) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_126.0',
  'food_name': 'Pheasant (Young)',
  'content': 'Pheasant (Young). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'pheasant (young) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_127.0',
  'food_name': 'Quail (Whole)',
  'content': 'Quail (Whole). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'quail (whole) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_128.0',
  'food_name': 'Capon (Whole)',
  'content': 'Capon (Whole). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'capon (whole) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_129.0',
  'food_name': 'Cornish Hens (Hens)',
  'content': 'Cornish Hens (Hens). Tip: Cooking times for poultry are for unstuffed birds. Check the internal temperature in the innermost part of the thigh, innermost part of the wing, and thickest part of the breast. Add 15 to 30 minutes for stuffed birds. Stuffed birds are ready when the internal temperature of stuffing reaches 165°F. | Cook to 165°F',
  'search_text': 'cornish hens (hens) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_144.0',
  'food_name': 'Lean fish (Cod)',
  'content': 'Lean fish (Cod). Tip: Cook until flesh is opaque and separates easily with a fork. | Cook to 145°F',
  'search_text': 'lean fish (cod) temperature cook safe',
  'type': 'safety'},
 {'id': 'safety_145.0',

In [22]:
# === COOKING DOCUMENTS ===
cooking_docs = []

cooking_with_names = cooking_df.merge(
    products_df[['Product_ID', 'Name', 'Keywords', 'Category_ID']], 
    on='Product_ID', 
    how='left'
)

for _, row in cooking_with_names.iterrows():
    food_name = row.get('Name', 'Unknown')
    if pd.isna(food_name):
        continue

    keywords = row.get('Keywords', '')
    specific_name = get_specific_name(food_name, keywords)
    cooking_parts = []
    
    if pd.notna(row.get('Cooking_Method')):
        cooking_parts.append(f"Method: {row['Cooking_Method']}")
    
    # Temperature
    if pd.notna(row.get('Cooking_Temperature')):
        temp_value = str(row['Cooking_Temperature'])
        cooking_parts.append(f"Temperature: {temp_value}°F")
    
    # Timing (handles from/to)
    if pd.notna(row.get('Timing_from')) and pd.notna(row.get('Timing_to')):
        time_from = row['Timing_from']
        time_to = row['Timing_to']
        metric = row.get('Timing_metric', 'minutes')
        
        # Clean up decimal .0 if present
        if isinstance(time_from, float) and time_from.is_integer():
            time_from = int(time_from)
        if isinstance(time_to, float) and time_to.is_integer():
            time_to = int(time_to)
        
        if pd.notna(row.get('Timing_per')):
            cooking_parts.append(f"Cook {time_from}-{time_to} {metric} per {row['Timing_per']}")
        else:
            cooking_parts.append(f"Cook for {time_from}-{time_to} {metric}")
    
    # Size/Measure (handles ranges)
    if pd.notna(row.get('Measure_from')) and pd.notna(row.get('Measure_to')):
        size_from = row['Measure_from']
        size_to = row['Measure_to']
        metric = row.get('Size_metric', 'pounds')
        
        if isinstance(size_from, float) and size_from.is_integer():
            size_from = int(size_from)
        if isinstance(size_to, float) and size_to.is_integer():
            size_to = int(size_to)
            
        cooking_parts.append(f"For {size_from}-{size_to} {metric} size")
    
    if cooking_parts:
        cooking_docs.append({
            'id': f"cooking_{row['Product_ID']}",
            'food_name': specific_name,
            'content': f"{keywords}. " + " | ".join(cooking_parts),
            'type': 'cooking'
        })

print(f"Cooking docs created: {len(cooking_docs)}")

Cooking docs created: 88

In [23]:
for doc in cooking_docs[:3]:
    print(f"\n{doc['content']}")

Beef,rib roast,bone-in,roast,bone,rib. Method: Oven | Temperature: 325.0°F | Cook 23-30 minutes per pound | For 4-8 pounds size

Beef,rib roast,boneless,rolled,roast,rib. Method: Oven | Temperature: 325.0°F | Cook 28-38 minutes per pound | For 4-6 pounds size

Beef,round,rump roast,roast. Method: Oven | Temperature: 325.0°F | Cook 30-35 minutes per pound | For 2.5-4 pounds size

In [24]:
# Saving for RAG
def save_collection(docs, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        for doc in docs:
            f.write(json.dumps(doc, ensure_ascii=False) + '\n')
    print(f"Saved {len(docs)} documents to {filename}")

save_collection(storage_docs, 'rag_storage.jsonl')
save_collection(safety_docs, 'rag_safety.jsonl')
save_collection(cooking_docs, 'rag_cooking.jsonl')

print("\n=== RAG Collections Created ===")
print(f"Storage docs: {len(storage_docs)}")
print(f"Safety docs: {len(safety_docs)}")
print(f"Cooking docs: {len(cooking_docs)}")

Saved 388 documents to rag_storage.jsonl
Saved 91 documents to rag_safety.jsonl
Saved 88 documents to rag_cooking.jsonl

=== RAG Collections Created ===
Storage docs: 388
Safety docs: 91
Cooking docs: 88